title: Dylan Hand
main-text: Dylan Hand
subtitle:
tagline: Official Site
logo: &profile-pic '/assets/img/optimized/profile-pic.jpg'
description: Official site of rapper extraordinaire Dylan Hand.
# baseurl: "/yo" # the subpath of your site, e.g. /blog
url: &url https://dylanhand.com


# Author Settings
author:
  name: Dylan Hand
  # tagline: rapper extraordinaire
  url: *url
  twitter: dylanhand
  image: *profile-pic


# Contact links
contact:
  - name: Instagram
    link: &instagram-link https://instagram.com/dylanhand
    icon: instagram
  - name: TikTok
    link: &tiktok-link https://www.tiktok.com/@dylan.hand
    icon: tiktok
  - name: Facebook
    link: https://facebook.com/dylanhand
    icon: facebook
  - name: Twitter
    link: &twitter-link https://twitter.com/dylanhand
    icon: twitter
  # - name: Bandcamp
  #   link: &bandcamp-link https://dylanhand.bandcamp.com/
  #   icon: bandcamp
  - name: Spotify
    link: &spotify-link https://open.spotify.com/artist/5jf6ZqP5NcRcNlyeqcbYWt?si=DSNjmhwsSDWYs2hrE9WmTg
    icon: spotify
  - name: Apple Music
    link: &apple-music-link https://music.apple.com/us/artist/dylan-hand/1525131681
    icon: itunes
  - name: SoundCloud
    link: &soundcloud-link https://soundcloud.com/dylanhand
    icon: soundcloud
  - name: YouTube
    link: &youtube-link https://www.youtube.com/@dhand
    icon: youtube


# Comment Section (Disqus)
disqus-identifier: # mr-brown # add your shortname for Disqus Comment. For example mr-brown


# Google Analytics
google-analytics: G-KRGRNSZ5Y9 # add your identifier. For example UA-99631805-1.


# Jekyll-seo-tag plugin
social:
  name: Dylan Hand
  links:
    - *instagram-link
    - *twitter-link
    - *tiktok-link
    - https://dylanhand.bandcamp.com/
    - *spotify-link
    - *apple-music-link
    - *soundcloud-link
    - *youtube-link

twitter:
  username: dylanhand

webmaster_verifications:
  google: Ra4QOQacatohZ32vQexONZdG_Gs6rQFJUvj-jBPd1F0


# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-sitemap
  - jekyll/tagging
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-feed

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext
  - scope:
      path: '_releases'
    values:
      seo:
        type: MusicRecording
  - scope:
      path: ''
    values:
      twitter:
        card: summary


include:
  - _pages
  - _links

# Collections
collections:
  releases: 
    output: true

# Tags
tag_page_dir:         tag
tag_page_layout:      tag-page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed


# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
